# Generated by Django 3.1.5 on 2021-01-31 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sold',
            new_name='is_sold',
        ),
        migrations.AddField(
            model_name='listing',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_bought', to=settings.AUTH_USER_MODEL),
        ),
    ]
