# Generated by Django 3.1.5 on 2021-01-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210131_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='items',
            new_name='item',
        ),
    ]
